### ISSUE TITLE
表格右上角-工具按钮，  点击 ‘列设置’ 按钮报错

### ISSUE THREAD

**Issue by mryfan** [ashuicoder/naive-ui-components#3]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'header')
    at getSlot (vuedraggable.js:59:24)
    at computeChildrenAndOffsets (vuedraggable.js:65:18)
    at Proxy.render1333 (vuedraggable.js:166:54)
    at renderComponentRoot (runtime-core.esm-bundler.js:887:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:6020:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:6151:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6161:5)
    at mountComponent (runtime-core.esm-bundler.js:5929:7)
    at processComponent (runtime-core.esm-bundler.js:5883:9)

**Comment by mryfan** [comment]
初步怀疑是对等依赖是 vuedraggable，已经是4年前的东西了，  建议升级至 vue-draggable-plus

**Comment by autumnLeaves-lady** [comment]
我刚看了。我们所有的在线项目和本地项目，这个拖拽的使用都是正常的。为保证线上项目正常运行维护，我们目前暂不更换依赖，避免因依赖更新出现其他问题。要不，你再找找原因？
